
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: check working directory
        run: pwd
      - name: Install dependencies
        run: npm ci
        working-directory: ../../  # Set the working directory
      
      - name: Install additional packages
        run: npm install
        working-directory: ../../  # Set the working directory
      
      - name: Run server
        run: npm run server
        working-directory: ../../  # Set the working directory
